### ISSUE TITLE
How the hell should dev server hosts work?

### ISSUE THREAD

**Issue by mipearson** [mipearson/webpack-rails#29]
Hi @bradfeehan @mattgibson @hotgazpacho @Aupajo @kagux

I don't use docker or virtual machines in my local development environment, so I think I've missed a use case when designing how Rails will retrieve the manifest file and how the assets will be communicated to the user.

The intention was that, despite what `dev_server.host` is set to, the `webpack-dev-server` would always be running on the same machine as the Rails server, via the `Procfile`. Thus, it'd always be available via `localhost` on the configured port. Obviously this is not always the case. Have I misunderstood something about how docker works?

Given the PRs that have been submitted I'm considering a mix of https://github.com/mipearson/webpack-rails/pull/28/ (in fact, making `request.host` the default) and https://github.com/mipearson/webpack-rails/pull/23, but I'm worried that this will make things too complicated and hinder future development & use.

I'm hoping that you can outline how you're using webpack-rails and how the current setup isn't working, so that we can agree on a universal & simple way forward.

**Comment by hotgazpacho** [comment]
So, docker is a native Linux thing (it relies on kernel hooks). In order to run docker on anything other than Linux, you need to have a Linux VM running. The happy path for this is docker-machine. Containers then run inside this VM, and through crazy routing and NAT, are exposed via private IP addresses. The practical effect is that localhost isn't an option.

There's the secondary matter of networking between containers. This occurs via a different network.

Finally, there's the fact that you're in effect running multiple machines; each container is its own Linux machine, each with it's own hostname. Tools like docker-compose provide a level of DNS and discovery among the containers. For example, you run a separate app and database container, you can address the db container from the app container as "database" or "postgres". Therefor, on the server-side code, you can't rely on the hostname of the machine running either rails or webpack dev server to provide a hostname that a web browser running on a host OS X machine can route to.

All that said, there's a project under way to bring a native-like docker experience to Mac and Windows. It's still in beta, but the upshot is that you can address exposed ports from docker containers via localhost. That said, docker-machine isn't going away anytime soon, and is still useful for isolated docker environments.

All that said, I hadn't considered inferring the hostname from the request, so that may well be a viable option.

**Comment by mipearson** [comment]
I get why the hostname that the browser sees must be configurable - but not the one that Rails uses to retrieve the manifest.

Are using docker-compose to run webpack-dev-server in a different container to the rails server, instead of using foreman to run both on the same container?

**Comment by kagux** [comment]
Hi, 

One of the reasons I have to run webpack outside of vm (and thus not being reachable by rails) is to have file events working. VM doesn't support inotify events and every single workaround is a major pain one way or another. 
Currently to make this setup work (rails on VM and webpack on host) I create an ssh tunnel to VM on webpack's port.

**Comment by hotgazpacho** [comment]
@mipearson with docker, the idea is to have each container do one and only one thing. For my app, for local development, I have half a dozen containers running:

- rails
- postgres
- sidekiq
- clockwork
- redis for sidekiq
- redis for cache
- webpack dev server 

Foreman doesn't come into play at all here; docker-compose takes care of orchestrating starting, stopping, and restarting containers. 

@kagux good point about the lack of inotify support. We are in the same situation with docker. We were just going to resort to polling. Perhaps running webpack dev server on the host is something I should look into.

Either way, we need to be able to configure the hostname that rails uses to retrieve the manifest.

**Comment by Aupajo** [comment]
I don't use Docker, so I can't contribute much to anything Docker-specific. I can talk about my use-case, though.

> The intention was that, despite what `dev_server.host` is set to, the `webpack-dev-server` would always be running on the same machine as the Rails server, via the `Procfile`.

This makes sense to me, and how I'm using it.

> Thus, it'd always be available via `localhost` on the configured port.

Consider the following cases:

1. Visiting the Rails app (say, `http://localhost:5000`) locally
2. Visiting the Rails app over the network (`http://192.168.1.12:5000`) on a mobile phone

By default, the HTML returns looks something like this:

```html
<script src="http://localhost:3808/webpack/output.js">
```

This works great in the first case, but will cause the second case to fail.

Ideally, the second case would return:

```html
<script src="http://192.168.1.20:3808/webpack/output.js">
```

Which is to say, the same host that the Rails app was accessed by.

This will allow the `webpack-dev-server` to run over the network (on the same machine as the Rails server).

My pull request, #28, allows you to use a proc as well as a hard-coded string for the dev host. This allows anyone to customise the dev server host at request time, and suit it to whatever fits their use-case best.

If you were to merge it, I'd suggest having a default of `-> { request.host }`, which will satisfy both cases above.

**Comment by mipearson** [comment]
I've integrated #23 and #28 in to the https://github.com/mipearson/webpack-rails/tree/DevHosts branch.

Note that I've renamed `server_host` and `server_port` to `manifest_host` and `manifest_port`.

**Comment by kagux** [comment]
awesome, thanks for your work @mipearson!

**Comment by mipearson** [comment]
Merged and will be released soon.
